# Generated by Django 3.1.1 on 2021-04-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20210427_0146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='snippet',
            name='highlighted',
            field=models.TextField(default=''),
        ),
    ]
